server:
  port: 9010

spring:
  application:
    name: notification-service

  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: notification-queue
          group: ${spring.application.name}
        emailsms-out-0:
          destination: account-notification-queue

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "fourstack"
    password: "stack4@2808"
    connection-timeout: 10s
